2022-03-02 09:03:29,522 - shuncom_main_2.py[line:760] - ERROR: 导出设备信息到execl表格 异常: [Errno 13] Permission denied: 'C:/Users/8370/Desktop/shuncom_Gateway_LAN_debugging_tool/Results/Export_data/测试数据.xlsx'
2022-03-02 09:04:09,210 - shuncom_main_2.py[line:760] - ERROR: 导出设备信息到execl表格 异常: [Errno 13] Permission denied: 'C:/Users/8370/Desktop/shuncom_Gateway_LAN_debugging_tool/Results/Export_data/测试数据.xlsx'
2022-03-02 14:23:57,277 - shuncom_main_2.py[line:894] - ERROR: udp_scanning_ip_mac 异常: can only concatenate list (not "str") to list
2022-03-02 14:24:56,528 - shuncom_main_2.py[line:895] - ERROR: udp_scanning_ip_mac 异常: can only concatenate list (not "str") to list
2022-03-02 14:25:23,915 - shuncom_main_2.py[line:895] - ERROR: udp_scanning_ip_mac 异常: can only concatenate list (not "str") to list
2022-03-02 14:34:51,642 - shuncom_main_2.py[line:894] - ERROR: udp_scanning_ip_mac 异常: 'list' object has no attribute 'split'
2022-03-02 15:56:47,953 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 16:00:30,782 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 16:02:51,550 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 16:03:19,258 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 16:03:22,153 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 16:03:22,187 - shuncom_main_2.py[line:334] - ERROR: add_device 异常: 'str' object has no attribute 'keys'
2022-03-02 18:00:36,654 - shuncom_main_2.py[line:893] - ERROR: udp_scanning_ip_mac 异常: 'NoneType' object has no attribute 'split'
