2022-02-08 11:59:47,229 - shuncom_main_2.py[line:465] - ERROR: Ë«»÷IP½øä¯ÀÀÆ÷ Òì³£: list index out of range
